import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate, useParams, useLocation } from 'react-router-dom';
import { QRCodeSVG as QRCode } from 'qrcode.react';
import {
  Activity, Archive, Bell, Brain, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight,
  CircleUserRound, Clock3, CloudUpload, Database, Eye, FileCheck2, FileKey2, FileSearch,
  FileSignature, FileText, Fingerprint, FolderOpen, Gauge, Globe2, History, KeyRound,
  LayoutDashboard, LockKeyhole, LogIn, LogOut, Menu, MoreHorizontal, Network, QrCode,
  Search, Settings as SettingsGear, Shield, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud, UserPlus,
  Users, X, Zap
} from 'lucide-react';
import './styles.css';

const demoUser = { name: 'John Kumar', role: 'Investigator', email: 'john.kumar@securedoc.in', department: 'Investigation' };

const seedEvidence = [
  { id:'EV-001', caseId:'CASE-101', title:'Firing Report', type:'PDF', status:'Verified', uploadedBy:'Police Officer', date:'18 Sep 2026' },
  { id:'EV-002', caseId:'CASE-102', title:'CCTV Footage', type:'Video', status:'Verified', uploadedBy:'Investigator', date:'16 Sep 2026' },
  { id:'EV-003', caseId:'CASE-103', title:'Forensic Report', type:'PDF', status:'Verified', uploadedBy:'Forensic Expert', date:'17 Sep 2026' },
  { id:'EV-004', caseId:'CASE-104', title:'Call Recording', type:'Audio', status:'Verified', uploadedBy:'Police Officer', date:'15 Sep 2026' },
  { id:'EV-005', caseId:'CASE-105', title:'Document Scan', type:'PDF', status:'Verified', uploadedBy:'Investigator', date:'15 Sep 2026' },
  { id:'EV-006', caseId:'CASE-106', title:'Image Evidence', type:'Image', status:'Verified', uploadedBy:'Admin', date:'14 Sep 2026' },
  { id:'EV-007', caseId:'CASE-107', title:'Report Draft', type:'PDF', status:'Verified', uploadedBy:'Investigator', date:'14 Sep 2026' },
  { id:'EV-008', caseId:'CASE-108', title:'Video Clip', type:'Video', status:'Verified', uploadedBy:'Police Officer', date:'13 Sep 2026' },
];

const seedLogs = [
  ['19 Sep 2026, 09:15 AM','John Kumar','Login','192.168.1.10','Successful'],
  ['19 Sep 2026, 09:12 AM','Raj Sharma','Upload','192.168.1.11','EV-001'],
  ['19 Sep 2026, 08:50 AM','Niha Singh','View','192.168.1.12','EV-001'],
  ['19 Sep 2026, 11:20 AM','Amit Verma','Verify','192.168.1.13','EV-002'],
  ['19 Sep 2026, 06:45 PM','Priya Patel','Logout','192.168.1.15','Session End'],
];

function useEvidence(){
  const [evidence,setEvidence] = useState(()=>JSON.parse(localStorage.getItem('securedoc_evidence')||'null') || seedEvidence);
  useEffect(()=>localStorage.setItem('securedoc_evidence',JSON.stringify(evidence)),[evidence]);
  return [evidence,setEvidence];
}

function Layout({children}){
  const [collapsed,setCollapsed]=useState(false);
  const nav = useNavigate();
  const location=useLocation();
  const links=[
    ['Dashboard','/dashboard',LayoutDashboard],['Upload Evidence','/upload',CloudUpload],['Evidence List','/evidence',FolderOpen],['AI Search','/ai-search',Brain],['Chain of Custody','/custody',Network],['Audit Logs','/audit',History],['Digital Signature','/signature',FileSignature],['QR Tracking','/qr-tracking',QrCode],['SettingsGear','/SettingsGear',SettingsGear]
  ];
  return <div className={'app '+(collapsed?'sidebar-collapsed':'')}>
    <aside className="sidebar">
      <div className="brand" onClick={()=>nav('/dashboard')}><div className="brand-icon"><ShieldCheck size={22}/></div><div><b>SecureDoc</b><small>Secure Digital Document Management System</small></div></div>
      <nav>{links.map(([label,to,Icon])=><NavLink key={to} to={to} className={({isActive})=>'nav-item '+(isActive?'active':'')}><Icon size={17}/><span>{label}</span></NavLink>)}</nav>
      <button className="sidebar-toggle" onClick={()=>setCollapsed(!collapsed)}><Menu size={18}/><span>{collapsed?'Expand':'Collapse'}</span></button>
      <div className="side-bottom"><div className="secure-pill"><LockKeyhole size={15}/> Secure session</div><button onClick={()=>nav('/login')}><LogOut size={16}/> <span>Logout</span></button></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="mobile-brand"><ShieldCheck size={20}/> SecureDoc</div><div className="top-actions"><button className="icon-btn"><Bell size={18}/><i></i></button><button className="profile" onClick={()=>nav('/SettingsGear')}><span className="avatar">JK</span><span><b>{demoUser.name}</b><small>{demoUser.role}</small></span><ChevronDown size={15}/></button></div></header>
      <div className="page-wrap">{children}</div>
    </main>
  </div>
}

function PageTitle({eyebrow,title,desc,action}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Stat({icon:Icon,label,value,delta,kind='blue'}){return <Card className="stat"><div className={'stat-icon '+kind}><Icon size={19}/></div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small className="positive">↗ {delta}</small></div></Card>}
function Status({children}){return <span className={'status '+children.toLowerCase().replace(' ','-')}><i></i>{children}</span>}

function Login(){
  const nav=useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const submit=(e)=>{e.preventDefault(); localStorage.setItem('securedoc_auth','1'); nav('/dashboard');};
  return <div className="auth-shell"><div className="auth-visual"><div className="auth-logo"><div className="brand-icon"><ShieldCheck/></div><div><b>SecureDoc</b><small>Secure Digital Document Management System</small></div></div><div className="auth-copy"><h1>Secure Evidence.<br/>Stronger Justice.</h1><p>A trusted platform for managing legal and investigation documents with end-to-end security, transparency, and AI-powered search.</p></div><div className="auth-shield"><Shield size={150}/></div><div className="auth-tags"><span>Encrypted</span><span>AI Powered</span><span>Audit Ready</span></div></div><div className="auth-form"><div className="auth-form-inner"><h2>Welcome Back</h2><p>Login to your account</p><form onSubmit={submit}><label>Email Address<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email" type="email" required/></label><label>Password<div className="input-icon"><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" type="password" required/><Eye size={17}/></div></label><div className="form-row"><label className="check"><input type="checkbox"/> Remember Me</label><button type="button" className="link-btn">Forgot Password?</button></div><button className="primary full"><LogIn size={17}/> Login</button></form><div className="or"><span>OR</span></div><button className="outline full" onClick={()=>nav('/dashboard')}><Fingerprint size={17}/> Login with OTP (MFA)</button><p className="bottom-note">Don't have an account? <button className="link-btn" onClick={()=>nav('/register')}>Register</button></p></div></div></div>
}

function Register(){const nav=useNavigate();return <div className="auth-shell"><div className="auth-visual register-visual"><div className="auth-logo"><div className="brand-icon"><ShieldCheck/></div><div><b>SecureDoc</b><small>Secure Digital Document Management System</small></div></div><div className="auth-copy"><h1>Secure Evidence.<br/>Stronger Justice.</h1><p>Join a secure network for legal & investigation services.</p></div><div className="auth-shield"><FileText size={150}/></div><div className="auth-tags"><span>Encrypted</span><span>AI Powered</span><span>Audit Ready</span></div></div><div className="auth-form"><div className="auth-form-inner"><h2>Create your Account</h2><p>Join a secure network for legal & investigation services.</p><form onSubmit={e=>{e.preventDefault();nav('/dashboard')}}><label>Full Name<input placeholder="Enter your full name" required/></label><label>Email Address<input type="email" placeholder="Enter your email" required/></label><label>Phone Number<input placeholder="Enter your phone number"/></label><label>Department<select><option>Select department</option><option>Investigation</option><option>Police</option><option>Forensic</option><option>Legal</option></select></label><label>Password<input type="password" placeholder="Create a strong password" required/></label><button className="primary full"><UserPlus size={17}/> Register</button></form><p className="bottom-note">Already have an account? <button className="link-btn" onClick={()=>nav('/login')}>Login</button></p></div></div></div>}

function Dashboard(){const [evidence]=useEvidence();return <><PageTitle eyebrow="OVERVIEW" title="Dashboard" desc={<>Welcome back, <b>{demoUser.name}</b>! Here's the latest overview of your system.</>}/><div className="stats-grid"><Stat icon={BriefcaseIcon} label="Total Cases" value="12" delta="15% from last week"/><Stat icon={FileCheck2} label="Total Evidence" value={evidence.length+40} delta="15% from last week" kind="cyan"/><Stat icon={Users} label="Active Users" value="8" delta="8% from last week" kind="purple"/><Stat icon={ShieldCheck} label="System Status" value="Secure" delta="All systems normal" kind="green"/></div><div className="dashboard-grid"><Card><div className="card-head"><div><h3>Evidence Uploads <small>(Last 7 Days)</small></h3></div><button className="ghost">View report</button></div><div className="fake-chart"><div className="chart-line"></div>{[20,48,32,56,39,68,52].map((v,i)=><div className="chart-point" key={i} style={{left:`${i*15+5}%`,bottom:`${v}%`}}><span>{i+1}</span></div>)}</div><div className="days"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></Card><Card><div className="card-head"><h3>Recent Activities</h3><button className="ghost">View all</button></div><div className="activity-list"><ActivityRow color="green" text="Evidence EV-001 uploaded" time="2 hours ago"/><ActivityRow color="blue" text="Case CASE-102 transferred" time="4 hours ago"/><ActivityRow color="orange" text="User admin logged in" time="6 hours ago"/><ActivityRow color="red" text="Evidence EV-001 verified" time="8 hours ago"/></div></Card></div><Card className="table-card"><div className="card-head"><h3>Recent Evidence</h3><NavLink to="/evidence" className="ghost">View All</NavLink></div><EvidenceTable rows={evidence.slice(0,4)}/></Card></>}
function BriefcaseIcon(){return <Archive size={19}/>}
function ActivityRow({color,text,time}){return <div className="activity-row"><span className={'activity-dot '+color}></span><span>{text}</span><time>{time}</time></div>}
function EvidenceTable({rows}){return <div className="table-scroll"><table><thead><tr><th>ID</th><th>Case ID</th><th>Title</th><th>Type</th><th>Status</th><th>Uploaded By</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.id}</b></td><td>{r.caseId}</td><td>{r.title}</td><td>{r.type}</td><td><Status>{r.status}</Status></td><td>{r.uploadedBy}</td><td>{r.date}</td></tr>)}</tbody></table></div>}

function Upload(){const [evidence,setEvidence]=useEvidence();const nav=useNavigate();const [file,setFile]=useState(null);const [caseId,setCaseId]=useState('');const [title,setTitle]=useState('');const [type,setType]=useState('PDF');const submit=()=>{if(!file||!caseId||!title)return alert('Please select a file and fill Case ID + Evidence Title.');const id='EV-'+String(evidence.length+1).padStart(3,'0');setEvidence([{id,caseId,title,type,status:'Verified',uploadedBy:demoUser.role,date:'23 Sep 2026'},...evidence]);setFile(null);setCaseId('');setTitle('');alert('Evidence uploaded in demo mode.');nav('/evidence');};return <><PageTitle eyebrow="EVIDENCE" title="Upload Evidence" desc="Upload new evidence with case details."/><div className="form-layout"><Card><div className="dropzone" onClick={()=>document.getElementById('file-input').click()}><UploadCloud size={42}/><h3>{file?file.name:'Drag & drop files here'}</h3><p>or</p><button className="outline">Choose Files</button><small>Supports: PDF, JPG, PNG, MP4, DOCX (Max 10MB)</small><input id="file-input" type="file" hidden onChange={e=>setFile(e.target.files[0])}/></div></Card><Card><h3>Evidence Details</h3><div className="form-grid"><label>Case ID<select value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Select Case ID</option><option>CASE-101</option><option>CASE-102</option><option>CASE-103</option><option>CASE-104</option></select></label><label>Evidence Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Enter evidence title"/></label><label className="full-field">Description<textarea placeholder="Enter description (optional)"/></label><label>Document Type<select value={type} onChange={e=>setType(e.target.value)}><option>PDF</option><option>Video</option><option>Audio</option><option>Image</option><option>DOCX</option></select></label></div><button className="primary full" onClick={submit}><CloudUpload size={17}/> Upload Evidence</button></Card></div></>}

function EvidenceList(){const [evidence]=useEvidence();const [q,setQ]=useState('');const filtered=evidence.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));return <><PageTitle eyebrow="DOCUMENT MANAGEMENT" title="Evidence List" desc="View and manage all uploaded evidence." action={<NavLink to="/upload" className="primary"><UploadCloud size={17}/> Upload Evidence</NavLink>}/><Card className="table-card"><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by Evidence ID, Case ID or Title..."/></div><button className="outline"><SlidersHorizontal size={16}/> Filter</button></div><EvidenceTable rows={filtered}/><div className="pagination"><span>Showing {filtered.length} of {evidence.length}</span><button><ChevronLeft size={15}/></button><button className="current">1</button><button>2</button><button>3</button><button><ChevronRight size={15}/></button></div></Card></>}

function Custody(){const steps=[['Police Upload','Raj Sharma (Police Officer)','18 Sep 2026, 09:15 AM','Completed'],['Investigator Review','Niha Sharma (Investigator)','18 Sep 2026, 12:20 PM','Completed'],['Forensic Verification','Amit Verma (Forensic Expert)','19 Sep 2026, 10:20 AM','Completed'],['Court Submission','My Court Officer','19 Sep 2026, 01:10 PM','In Progress']];return <><PageTitle eyebrow="TRACEABILITY" title="Chain of Custody" desc="Track the complete journey of evidence." action={<button className="outline"><Search size={16}/> Search Evidence</button>}/><Card className="custody-card"><div className="custody-search"><div className="search"><Search size={17}/><input defaultValue="EV-001" placeholder="Search by Evidence ID, Case ID or Title..."/></div><button className="primary">View</button></div><div className="timeline">{steps.map((s,i)=><div className="timeline-row" key={s[0]}><div className={'timeline-icon '+(i===3?'progress':'')}><span>{i===3?'4':'✓'}</span></div><div className="timeline-content"><div><b>{i+1}. {s[0]}</b><span className={'step-status '+(i===3?'progress':'')}>{s[3]}</span></div><p>By {s[1]}</p><small>{s[2]}</small></div></div>)}</div></Card></>}

function Audit(){return <><PageTitle eyebrow="SECURITY" title="Audit Logs" desc="Track all system activities and user actions."/><Card className="table-card"><div className="filters"><label>From Date<input type="date" defaultValue="2026-09-01"/></label><label>To Date<input type="date" defaultValue="2026-09-23"/></label><label>Action<select><option>All</option><option>Login</option><option>Upload</option><option>View</option><option>Verify</option></select></label><button className="primary">Search</button></div><div className="table-scroll"><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>IP Address</th><th>Details</th></tr></thead><tbody>{seedLogs.map((r,i)=><tr key={i}><td>{r[0]}</td><td><b>{r[1]}</b></td><td><span className="action-tag">{r[2]}</span></td><td>{r[3]}</td><td>{r[4]}</td></tr>)}</tbody></table></div></Card></>}

async function createSignature(text){const data=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
function Signature(){const [evidence]=useEvidence();const [selected,setSelected]=useState(evidence[0]?.id||'EV-001');const [signature,setSignature]=useState(null);const [busy,setBusy]=useState(false);const [qr,setQr]=useState('');const selectedDoc=evidence.find(x=>x.id===selected)||evidence[0];const sign=async()=>{setBusy(true);const hash=await createSignature(`${selectedDoc.id}|${selectedDoc.caseId}|${selectedDoc.title}|${selectedDoc.date}`);setSignature({hash,certificate:'SDC-CERT-2026-001',signedBy:demoUser.name,time:new Date().toLocaleString()});const url=`${window.location.origin}/#/track/${selectedDoc.id}`;setQr(url);setBusy(false)};return <><PageTitle eyebrow="TRUST & AUTHENTICITY" title="Digital Signature" desc="Sign documents securely with a browser-based cryptographic demo."/><div className="signature-grid"><Card><h3>Sign Document</h3><label>Select Document<select value={selected} onChange={e=>setSelected(e.target.value)}>{evidence.map(x=><option key={x.id}>{x.id} — {x.title}</option>)}</select></label><div className="certificate-box"><div className="cert-icon"><FileKey2 size={24}/></div><div><b>SecureDoc Digital Certificate</b><p>PKI-style demo certificate • SHA-256 document fingerprint</p></div><Status>Valid Certificate</Status></div><label>Reason for Signature<textarea defaultValue="Evidence authenticity verification"/></label><div className="sign-info"><ShieldCheck size={18}/><span>Your document will be signed using a cryptographic hash in this frontend demo. Backend PKI/HSM integration can replace this for production.</span></div><button className="primary full" onClick={sign} disabled={busy}><FileSignature size={17}/>{busy?'Signing...':'Sign Document'}</button></Card><Card><h3>Digital Certificate</h3>{signature?<><div className="valid-banner"><CheckCircle2 size={18}/><div><b>Valid Certificate</b><small>Signed successfully</small></div></div><div className="detail-list"><div><span>Signed To</span><b>{signature.signedBy}</b></div><div><span>Certificate</span><b>{signature.certificate}</b></div><div><span>SHA-256 Fingerprint</span><code>{signature.hash.slice(0,30)}...</code></div><div><span>Signed At</span><b>{signature.time}</b></div></div><div className="qr-mini"><QRCode value={qr} size={118}/><div><b>QR Tracking</b><p>Scan to open the public evidence tracking view.</p><small>{selectedDoc.id}</small></div></div></>:<div className="empty-state"><FileSignature size={40}/><b>No signature yet</b><p>Select a document and click Sign Document.</p></div>}</Card></div><Card className="signature-banner"><div className="banner-icon"><FileSignature size={46}/></div><div><h2>Digital Signature</h2><p>Authenticate · Verify · Protect</p><ul><li>PKI-ready digital signature workflow</li><li>Document fingerprint prevents unnoticed changes</li><li>Non-repudiation support</li><li>Designed for court-ready evidence workflows</li></ul></div></Card></>}

function QRTracking(){const {id}=useParams();const [evidence]=useEvidence();const doc=evidence.find(x=>x.id===id)||evidence[0];const trackingUrl=`${window.location.origin}/#/track/${doc.id}`;return <div className="tracking-page"><div className="tracking-header"><div className="brand"><div className="brand-icon"><ShieldCheck/></div><div><b>SecureDoc</b><small>Evidence Verification Portal</small></div></div><span className="public-pill"><Globe2 size={14}/> Public verification</span></div><div className="tracking-card"><div className="qr-large"><QRCode value={trackingUrl} size={180}/></div><div className="verified-title"><CheckCircle2 size={22}/> Evidence record found</div><h1>{doc.id}</h1><p className="tracking-sub">Secure tracking record for <b>{doc.title}</b></p><div className="tracking-details"><div><span>Case ID</span><b>{doc.caseId}</b></div><div><span>Document Type</span><b>{doc.type}</b></div><div><span>Uploaded By</span><b>{doc.uploadedBy}</b></div><div><span>Status</span><Status>{doc.status}</Status></div><div><span>Upload Date</span><b>{doc.date}</b></div><div><span>Integrity</span><b className="green-text">SHA-256 verified</b></div></div><div className="track-timeline"><div><i></i><span><b>Uploaded</b><small>Evidence registered in SecureDoc</small></span></div><div><i></i><span><b>Verified</b><small>Record marked as verified</small></span></div><div><i></i><span><b>Traceable</b><small>Chain of custody available to authorized users</small></span></div></div><button className="outline" onClick={()=>window.print()}><FileCheck2 size={16}/> Print verification</button></div><p className="tracking-foot">SecureDoc · Secure · Intelligent · Court-Ready</p></div>}

function AISearch(){const [q,setQ]=useState('');const suggestions=['All cases related to a person','Evidence by date range','Evidence uploaded last 7 days','Forensic reports','Audio files'];return <><PageTitle eyebrow="INTELLIGENCE" title="AI Powered Search" desc="Find evidence, cases, and documents using natural language."/><Card className="ai-card"><div className="ai-search"><div className="search"><Sparkles size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={'e.g. “Show me all CCTV footage from CASE-102”'}/></div><button className="primary">Search</button></div><div className="suggestion-title">Suggested Searches</div><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>setQ(s)}>{s}</button>)}</div><div className="ai-empty"><Brain size={48}/><h3>Ask anything...</h3><p>Use natural language to search across all your documents and evidence.</p></div></Card></>}
function Settings(){const [tab,setTab]=useState('Profile');return <><PageTitle eyebrow="PREFERENCES" title="SettingsGear" desc="Manage your account, security and system preferences."/><div className="SettingsGear-layout"><Card className="SettingsGear-menu">{['Profile','Security','Notifications','Appearance','System'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}><SettingsIcon tab={t}/>{t}</button>)}</Card><Card><h3>{tab}</h3>{tab==='Profile'?<div className="profile-SettingsGear"><div className="big-avatar">JK</div><label>Name<input defaultValue={demoUser.name}/></label><label>Email<input defaultValue={demoUser.email}/></label><label>Department<input defaultValue={demoUser.department}/></label><button className="primary">Update Profile</button></div>:<div className="SettingsGear-placeholder"><ShieldCheck size={42}/><h3>{tab} SettingsGear</h3><p>Frontend demo controls for the SecureDoc prototype.</p></div>}</Card></div></>}
function SettingsIcon({tab}){const I=tab==='Profile'?CircleUserRound:tab==='Security'?ShieldCheck:tab==='Notifications'?Bell:tab==='Appearance'?SlidersHorizontal:SettingsGear;return <I size={16}/>}
function Protected(){return localStorage.getItem('securedoc_auth')?<Layout><Routes><Route path="/dashboard" element={<Dashboard/>}/><Route path="/upload" element={<Upload/>}/><Route path="/evidence" element={<EvidenceList/>}/><Route path="/ai-search" element={<AISearch/>}/><Route path="/custody" element={<Custody/>}/><Route path="/audit" element={<Audit/>}/><Route path="/signature" element={<Signature/>}/><Route path="/qr-tracking" element={<QRTrackingHome/>}/><Route path="/SettingsGear" element={<SettingsGear/>}/><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></Layout>:<Navigate to="/login" replace/>}
function QRTrackingHome(){const [evidence]=useEvidence();return <><PageTitle eyebrow="VERIFICATION" title="QR Tracking" desc="Generate and test QR links for evidence verification."/><Card><div className="qr-home-grid">{evidence.slice(0,6).map(doc=><div className="qr-card" key={doc.id}><QRCode value={`${window.location.origin}/#/track/${doc.id}`} size={110}/><div><b>{doc.id}</b><p>{doc.title}</p><Status>{doc.status}</Status><NavLink className="link-btn" to={`/track/${doc.id}`}>Open tracking</NavLink></div></div>)}</div></Card></>}
function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/track/:id" element={<QRTracking/>}/><Route path="/*" element={<Protected/>}/></Routes>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);








